#Ansible Playbook to deploy Terraform

- name: Deploy Terraform
  hosts: localhost
  tasks:
    - name: Define backend_configuration
       terraform:
         project_path: 'NTTData/Ansibleplaybook'
         state:present                            
         force_init: true
         backend_config:
           bucket:"NTTDATA"            
           region:"ap-south-1"
           key:"nttdata.tfstate"
      
    - name: Deploying the Infra
       EC2 instance:
       name:"NTTdata  # ec2 instance name
  
